"""Add dataset counters to user_profile

Revision ID: fd895fb8a9b3
Revises: 001
Create Date: 2025-11-10 09:41:40.118426

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "002"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("webhook")
    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uploaded_datasets_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("downloaded_datasets_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("synchronized_datasets_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.drop_column("synchronized_datasets_count")
        batch_op.drop_column("downloaded_datasets_count")
        batch_op.drop_column("uploaded_datasets_count")

    op.create_table(
        "webhook",
        sa.Column("id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
