"""Delete seed for food_checker

Revision ID: 712242dc1697
Revises: 002
Create Date: 2025-12-05 13:12:57.512788

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "004"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("webhook", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.drop_table("food_checker")
    with op.batch_alter_table("base_author", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_author_food_metadata", "food_meta_data", ["food_meta_data_id"], ["id"], use_alter=True
        )
        batch_op.create_foreign_key(
            "fk_author_food_ds_metadata", "food_ds_meta_data", ["food_ds_meta_data_id"], ["id"], use_alter=True
        )

    with op.batch_alter_table("food_dataset", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_food_dataset_ds_metadata", "food_ds_meta_data", ["ds_meta_data_id"], ["id"], use_alter=True
        )

    with op.batch_alter_table("food_nutritional_value", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_nutritional_val_ds_metadata", "food_ds_meta_data", ["ds_meta_data_id"], ["id"], use_alter=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("food_nutritional_value", schema=None) as batch_op:
        batch_op.drop_constraint("fk_nutritional_val_ds_metadata", type_="foreignkey")

    with op.batch_alter_table("food_dataset", schema=None) as batch_op:
        batch_op.drop_constraint("fk_food_dataset_ds_metadata", type_="foreignkey")

    with op.batch_alter_table("base_author", schema=None) as batch_op:
        batch_op.drop_constraint("fk_author_food_ds_metadata", type_="foreignkey")
        batch_op.drop_constraint("fk_author_food_metadata", type_="foreignkey")

    op.create_table(
        "food_checker",
        sa.Column("id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("webhook")
    # ### end Alembic commands ###
