"""Add missing trending columns

Revision ID: f35b3d8bb0ee
Revises: 004
Create Date: 2025-12-08 12:25:59.065112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35b3d8bb0ee'
down_revision = '712242dc1697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_dataset_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['food_dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_dataset_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_dataset_activity_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_dataset_activity_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_dataset_activity_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('food_dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('download_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_viewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_downloaded_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('food_ds_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_ds_meta_data', schema=None) as batch_op:
        batch_op.drop_column('community')

    with op.batch_alter_table('food_dataset', schema=None) as batch_op:
        batch_op.drop_column('last_downloaded_at')
        batch_op.drop_column('last_viewed_at')
        batch_op.drop_column('download_count')
        batch_op.drop_column('view_count')

    with op.batch_alter_table('food_dataset_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_dataset_activity_timestamp'))
        batch_op.drop_index(batch_op.f('ix_food_dataset_activity_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_food_dataset_activity_activity_type'))

    op.drop_table('food_dataset_activity')
    # ### end Alembic commands ###
