"""Add ds_metrics relationship to BaseDSMetaData

Revision ID: 6c414d046782
Revises: 95604a597aea
Create Date: 2025-12-13 12:44:49.745880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c414d046782'
down_revision = '95604a597aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ds_metrics_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ds_metrics', ['ds_metrics_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ds_metrics_id')

    # ### end Alembic commands ###
