"""Add Shopping Cart

Revision ID: 95604a597aea
Revises: 0afb187a38df
Create Date: 2025-12-12 20:20:19.406469

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "007"
down_revision = "006"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shopping_cart",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("food_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shoppingcart_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "shopping_cart", ["shoppingcart_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("food_dataset", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("shoppingcart_id")

    op.drop_table("shopping_cart")
    # ### end Alembic commands ###
