"""Add download_count and view_count to FoodModel

Revision ID: b9b7f834559e
Revises: 6c414d046782
Create Date: 2025-12-14 18:27:57.051055

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "009"
down_revision = "008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ds_metrics", schema=None) as batch_op:
        batch_op.add_column(sa.Column("number_of_features", sa.String(length=120), nullable=True))

    with op.batch_alter_table("food_model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("download_count", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("view_count", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("food_model", schema=None) as batch_op:
        batch_op.drop_column("view_count")
        batch_op.drop_column("download_count")

    with op.batch_alter_table("ds_metrics", schema=None) as batch_op:
        batch_op.drop_column("number_of_features")

    # ### end Alembic commands ###
