"""final_migration

Revision ID: 17f3b6401236
Revises: c1addf000001
Create Date: 2025-12-15 17:49:24.336174

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "011"
down_revision = "010"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("fakenodo", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_table(
        "shopping_cart",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("zenodo")
    with op.batch_alter_table("base_author", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_author_food_metadata", "food_meta_data", ["food_meta_data_id"], ["id"], use_alter=True
        )
        batch_op.create_foreign_key(
            "fk_author_food_ds_metadata", "food_ds_meta_data", ["food_ds_meta_data_id"], ["id"], use_alter=True
        )

    with op.batch_alter_table("ds_meta_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ds_metrics_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "ds_metrics", ["ds_metrics_id"], ["id"])

    with op.batch_alter_table("ds_metrics", schema=None) as batch_op:
        batch_op.add_column(sa.Column("number_of_features", sa.String(length=120), nullable=True))

    with op.batch_alter_table("food_dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shoppingcart_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "shopping_cart", ["shoppingcart_id"], ["id"])
        batch_op.create_foreign_key(
            "fk_food_dataset_ds_metadata", "food_ds_meta_data", ["ds_meta_data_id"], ["id"], use_alter=True
        )

    with op.batch_alter_table("food_model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("download_count", sa.Integer(), server_default=sa.text("0"), nullable=False))
        batch_op.add_column(sa.Column("view_count", sa.Integer(), server_default=sa.text("0"), nullable=False))

    with op.batch_alter_table("food_nutritional_value", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_nutritional_val_ds_metadata", "food_ds_meta_data", ["ds_meta_data_id"], ["id"], use_alter=True
        )

    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uploaded_datasets_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("downloaded_datasets_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("synchronized_datasets_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_profile", schema=None) as batch_op:
        batch_op.drop_column("synchronized_datasets_count")
        batch_op.drop_column("downloaded_datasets_count")
        batch_op.drop_column("uploaded_datasets_count")

    with op.batch_alter_table("food_nutritional_value", schema=None) as batch_op:
        batch_op.drop_constraint("fk_nutritional_val_ds_metadata", type_="foreignkey")

    with op.batch_alter_table("food_model", schema=None) as batch_op:
        batch_op.drop_column("view_count")
        batch_op.drop_column("download_count")

    with op.batch_alter_table("food_dataset", schema=None) as batch_op:
        batch_op.drop_constraint("fk_food_dataset_ds_metadata", type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("shoppingcart_id")

    with op.batch_alter_table("ds_metrics", schema=None) as batch_op:
        batch_op.drop_column("number_of_features")

    with op.batch_alter_table("ds_meta_data", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("ds_metrics_id")

    with op.batch_alter_table("base_author", schema=None) as batch_op:
        batch_op.drop_constraint("fk_author_food_ds_metadata", type_="foreignkey")
        batch_op.drop_constraint("fk_author_food_metadata", type_="foreignkey")

    op.create_table(
        "zenodo",
        sa.Column("id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("shopping_cart")
    op.drop_table("fakenodo")
    # ### end Alembic commands ###
