"""add download history tables

Revision ID: 11e45816bad6
Revises: 0498a4b399d3
Create Date: 2025-12-16 00:19:33.862843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e45816bad6'
down_revision = '0498a4b399d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_record_datasets',
    sa.Column('download_record_id', sa.Integer(), nullable=False),
    sa.Column('food_dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['download_record_id'], ['download_record.id'], ),
    sa.ForeignKeyConstraint(['food_dataset_id'], ['food_dataset.id'], ),
    sa.PrimaryKeyConstraint('download_record_id', 'food_dataset_id')
    )
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_features', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.drop_column('number_of_features')

    op.drop_table('download_record_datasets')
    op.drop_table('download_record')
    # ### end Alembic commands ###
