"""empty message

Revision ID: 1c873f197e8a
Revises: eb12bd4189a7
Create Date: 2025-12-11 16:06:11.500773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c873f197e8a'
down_revision = 'eb12bd4189a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fakenodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('webhook')
    op.drop_table('doi_mapping')
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_datasets_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('downloaded_datasets_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('synchronized_datasets_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('synchronized_datasets_count')
        batch_op.drop_column('downloaded_datasets_count')
        batch_op.drop_column('uploaded_datasets_count')

    op.create_table('doi_mapping',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('dataset_doi_old', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('dataset_doi_new', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('webhook',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('fakenodo')
    # ### end Alembic commands ###
