"""empty message

Revision ID: 5be846a0b178
Revises: 56e3e49b6717
Create Date: 2025-11-11 08:25:34.247907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be846a0b178'
down_revision = '56e3e49b6717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uvl_dataset_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_features', sa.Integer(), nullable=True),
    sa.Column('total_constraints', sa.Integer(), nullable=True),
    sa.Column('model_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['dataset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('is_email_verified')

    op.drop_table('uvl_dataset_version')
    # ### end Alembic commands ###
