"""uvlfilename to filename

Revision ID: fe5f1971ef42
Revises: e832c31ecfc1
Create Date: 2025-11-10 13:11:17.307099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe5f1971ef42'
down_revision = 'e832c31ecfc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uvl_dataset_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_features', sa.Integer(), nullable=True),
    sa.Column('total_constraints', sa.Integer(), nullable=True),
    sa.Column('model_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['dataset_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=120), nullable=False))
        batch_op.drop_column('uvl_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('filename')

    op.drop_table('uvl_dataset_version')
    # ### end Alembic commands ###
