# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By

pytestmark = pytest.mark.selenium


class TestAdddataset:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_adddataset(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(602, 819)
        self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) .btn:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) .btn:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(4) .btn:nth-child(3)").click()

    def test_showshoppingcart(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(602, 819)
        self.driver.find_element(By.CSS_SELECTOR, ".feather-shopping-cart > circle:nth-child(2)").click()

    def test_deletedataset(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(602, 819)
        self.driver.find_element(By.CSS_SELECTOR, ".feather-shopping-cart").click()
        self.driver.find_element(By.LINK_TEXT, "Remove").click()
        self.driver.find_element(By.LINK_TEXT, "Remove").click()
        self.driver.find_element(By.LINK_TEXT, "Remove").click()
        self.driver.find_element(By.LINK_TEXT, "Remove").click()
