# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

pytestmark = pytest.mark.selenium

class TestAdddataset():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adddataset(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(602, 819)
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) .btn:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) .btn:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(4) .btn:nth-child(3)").click()

  def test_showshoppingcart(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(602, 819)
    self.driver.find_element(By.CSS_SELECTOR, ".feather-shopping-cart > circle:nth-child(2)").click()

  def test_deletedataset(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(602, 819)
    self.driver.find_element(By.CSS_SELECTOR, ".feather-shopping-cart").click()
    self.driver.find_element(By.LINK_TEXT, "Remove").click()
    self.driver.find_element(By.LINK_TEXT, "Remove").click()
    self.driver.find_element(By.LINK_TEXT, "Remove").click()
    self.driver.find_element(By.LINK_TEXT, "Remove").click()
  
